name: Linting & Tests
on:
  pull_request:
    branches:
      - main
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
      - name: Install dependencies
        run: flutter pub get
      - name: Run Dart Format Check
        run: |
          dart format . --set-exit-if-changed --output none || (
            echo "Code formatting issues detected. Run 'dart format .' and commit the changes.";
            exit 1;
          )
      - name: Run Flutter Analyze
        run: flutter analyze
      - name: Run Dart Format and Check Localization Files Changes
        run: |
          # Run dart format without failing the step
          dart format . || echo "dart format completed with warnings, but continuing pipeline."
          
          # Check if there are changes in the localization files after generation
          git diff --exit-code lib/src/core/utils/gen/localization || (
            echo "Error: Localization files are outdated. Run the generation command and commit the changes.";
            exit 1;
          )
      - name: Run tests
        run: flutter test
  merge_check:
    runs-on: ubuntu-latest
    needs: lint_and_test
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge Pull Request
        run: echo "Linting and tests passed successfully.Merge request is ready for merge"